### PR TITLE
Add order id to the shipping label

### PR DESCRIPTION
**Pull request by Abdalsalaam**

### CODE REVIEW

**Comment by rob1998** [comment]
Hi, I believe it would make more sense to use the order number instead of the id: https://woocommerce.github.io/code-reference/classes/WC-Order.html#method_get_order_number

**Comment by Abdalsalaam** [comment]
> 

Thank you, i did this change

**Review by iyut — APPROVED** [review]
the changes looks good to me!

**Comment by rob1998** [comment]
Hey thanks, I just tested it on a development environment and seems to work great! Just installed on production and informed our client. Should any bugs appear, I will report them as a new issue.

Solves #34

**Pull request merged**
